spring.application.name=finance-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance-api}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:toninho}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET:5b6f8d2a1e4c7f9b3d0e2a5c8f1b4d7e9a2c5f8b1d4e7a0c3f6b9d2e5a8c1f4}
jwt.expiration=${JWT_EXPIRATION:86400000}