spring.application.name=finance-api
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=5b6f8d2a1e4c7f9b3d0e2a5c8f1b4d7e9a2c5f8b1d4e7a0c3f6b9d2e5a8c1f4
jwt.expiration=86400000